export const InitQuery = {
	brand: "HP",
	creator: "",
	cur_config: "",
	decision: "",
	is_fraud: false,
	is_junk: false,
	is_need_war: false,
	lb_type: "Amazon",
	model: "",
	order_id: "",
	rt_dt:"",
	rec_dt:"",
	rt_cmt: "",
	rt_cmt_cs: "",
	rt_qty: "1",
	rt_reason: "",
	rt_track: "",
	seller: "",
	sn: "",
	upc: "",
	war_case: "",
	war_cmt: "",
	war_method: "Factory",
	war_opr: "",
	war_track_in: "",
	war_track_out: "",
	war_def:"",
	pics:[]
}